name: Generate and upload folders

inputs:
  working_directory:
    description: 'Working directory'
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate folders
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        # Extract the basename of the working directory
        BASENAME=$(basename "${{ inputs.working_directory }}")
        # Create a directory in the docs folder for each project and move all the files there
        mkdir -p ../docs/${BASENAME}
        # create index.html with simple hello world
        # Create an index.html file with a simple "Hello World" message
        echo '<!DOCTYPE html>
        <html>
        <head>
            <title>Hello World</title>
        </head>
        <body>
            <h1>Hello World from '"${BASENAME}"'</h1>
        </body>
        </html>' > ../docs/${BASENAME}/index.html
        echo "Created ../docs/${BASENAME}/index.html with Hello World content."
