name: Publish multiple pages

on:
  push:
    branches:
      - main

jobs:
  create-folders:
    name: Create folders
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pages: write

    # create one job for each of projects
    strategy:
      fail-fast: false
      matrix:
        working_directory: [./folder1, ./folder2]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate and upload folders and artifacts
        uses: ./.github/workflows/actions/generate-upload-folders
        with:
          working_directory: ${{ matrix.working_directory }}

      - name: Normalise Folder Name
        id: normalise-folder
        run: |
          # Remove the './' prefix from the working_directory
          NORMALISED_FOLDER=$(echo "${{ matrix.working_directory }}" | sed 's|^\./||')
          echo "normalised_folder=$NORMALISED_FOLDER" >> $GITHUB_ENV

      # - name: Upload Folder Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     # Use the normalised folder name for the artifact name and path
      #     name: docs-${{ env.normalised_folder }}
      #     path: ./docs/${{ env.normalised_folder }}

      - name: Upload Normalised Folders Artifact
        uses: actions/upload-artifact@v4
        with:
          name: normalised-folders
          path: ./normalised_folders.txt

  upload-docs-artifact-and-publish:
    name: Upload and publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pages: write

    needs: create-folders

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Normalised Folders Artifact
        uses: actions/download-artifact@v4
        with:
          name: normalised-folders

      - name: Read Normalised Folders and Download Artifacts
        run: |
          # Read the list of normalised folders from the artifact
          while IFS= read -r folder; do
            echo "Downloading artifact for $folder"
            mkdir -p ./docs/$folder
            actions/download-artifact@v4 --name docs-$folder --path ./docs/$folder
          done < normalised_folders.txt

      - name: Create root index HTML
        uses: ./.github/workflows/actions/create-root-index-html
        with:
          # Dynamically pass the list of projects
          projects: "[./folder1, ./folder2]"

      - name: Upload Combined Docs Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy Docs to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Set Up Github Pages Environment Variables
        env:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        uses: actions/configure-pages@v5
